//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomatedTimetableGeneration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course()
        {
            this.Doctor_Available_Time = new HashSet<Doctor_Available_Time>();
            this.LinkCourseDepts = new HashSet<LinkCourseDept>();
            this.LinkDoctorCourses = new HashSet<LinkDoctorCourse>();
            this.SectionTimes = new HashSet<SectionTime>();
            this.Ta_Wishes = new HashSet<Ta_Wishes>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int Hours { get; set; }
        public bool HaveLab { get; set; }
        public bool HaveSection { get; set; }
        public Nullable<int> LabHours { get; set; }
        public Nullable<int> SectionHours { get; set; }
        public Nullable<int> RoomType_id { get; set; }
        public int AcademicYear_id { get; set; }
        public Nullable<int> StaffCount { get; set; }
    
        public virtual AcademicYear AcademicYear { get; set; }
        public virtual RoomType RoomType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Doctor_Available_Time> Doctor_Available_Time { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LinkCourseDept> LinkCourseDepts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LinkDoctorCourse> LinkDoctorCourses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SectionTime> SectionTimes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ta_Wishes> Ta_Wishes { get; set; }
    }
}
