//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomatedTimetableGeneration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LectureTime
    {
        public int ID { get; set; }
        public int Course_id { get; set; }
        public int Room_id { get; set; }
        public int DayOfWeek { get; set; }
        public int StartHour { get; set; }
        public Nullable<int> Grp_id { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Room Room { get; set; }
    }
}
