//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomatedTimetableGeneration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SectionTime
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SectionTime()
        {
            this.LinkTaSectionTimes = new HashSet<LinkTaSectionTime>();
        }
    
        public int ID { get; set; }
        public int Section_id { get; set; }
        public int Room_id { get; set; }
        public int DayOfWeek { get; set; }
        public int Course_id { get; set; }
        public Nullable<bool> isSection { get; set; }
        public Nullable<bool> isLab { get; set; }
        public Nullable<int> StartHour { get; set; }
        public string Ta_id { get; set; }
    
        public virtual Course Course { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LinkTaSectionTime> LinkTaSectionTimes { get; set; }
        public virtual Room Room { get; set; }
        public virtual Section Section { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
